name       : klayout
version    : 0.25.2
release    : 3
source     :
    - http://www.klayout.org/downloads/source/klayout-0.25.2.tar.bz2 : 182d5c4bed4ea0d107cb22e4721e36f7111875bcdfc93a82aa10da4663dc7aff
license    :
    - GPL-2.0-or-later
component  : office.scientific
summary    : Klayout GDS/OASIS editor
description: |
    High performance layout viewer and editor that supports GDS and OASIS files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(python3)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(ruby-2.3)
replaces   :
    - klayout-devel
setup      : |
    ./build.sh -dry-run
build      : |
    cd build-release
    %make
install    : |
    ## Binaries
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 build-release/{klayout,strm*} $installdir/usr/bin/.

    ## Libraries
    install -D -d -m 00755 $installdir/%libdir%
    install -m 00644 build-release/libklayout*.so.0 $installdir/%libdir%/.
    ## use cp+chmod because install resolve
    cp -d build-release/libklayout*.so.0.* $installdir/%libdir%/.
    chmod 00644 $installdir/%libdir%/libklayout*.so.0.*

    ## Menu Files    
    install -D -m 00644 etc/logo.png $installdir/usr/share/pixmaps/klayout.png
    install -D -m 00644 $pkgfiles/klayoutEditor.desktop $installdir/usr/share/applications/klayoutEditor.desktop
    install -D -m 00644 $pkgfiles/klayoutViewer.desktop $installdir/usr/share/applications/klayoutViewer.desktop
