name       : klayout
version    : 0.25.6
release    : 6
source     :
    - https://www.klayout.org/downloads/source/klayout-0.25.6.tar.bz2 : 7d9492c0c74c8d3b1277392212d3bf5a4f63b159f3542168c0fe0a70d6f92775
license    :
    - GPL-2.0-or-later
component  : office.scientific
summary    : Klayout GDS/OASIS editor
description: |
    High performance layout viewer and editor that supports GDS and OASIS files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(python3)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(ruby-2.6)
replaces   :
    - klayout-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-missing-OP.patch
    ./build.sh -dry-run -qt5
build      : |
    cd build-release
    %make
install    : "## Binaries\ninstall -D -d -m 00755 $installdir/usr/bin\ninstall -m\
    \ 00755 build-release/{klayout,strm*} $installdir/usr/bin/.\n\n## Libraries\n\
    install -D -d -m 00755 $installdir/%libdir%\ninstall -m 00644 build-release/libklayout*.so.0\
    \ $installdir/%libdir%/.\n## use cp+chmod because install resolve\ncp -d build-release/libklayout*.so.0.*\
    \ $installdir/%libdir%/.\nchmod 00644 $installdir/%libdir%/libklayout*.so.0.*\n\
    \n## Menu Files    \ninstall -D -m 00644 etc/logo.png $installdir/usr/share/pixmaps/klayout.png\n\
    install -D -m 00644 $pkgfiles/klayoutEditor.desktop $installdir/usr/share/applications/klayoutEditor.desktop\n\
    install -D -m 00644 $pkgfiles/klayoutViewer.desktop $installdir/usr/share/applications/klayoutViewer.desktop\n"
