name       : klayout
version    : 0.26.1
release    : 12
source     :
    - https://github.com/KLayout/klayout/archive/v0.26.1.tar.gz : 9619dd86cdfdb5aee43184a3edd2a24295028daf615cee52c6bee02fabcd8952
license    :
    - GPL-2.0-or-later
component  : office.scientific
summary    : Klayout GDS/OASIS editor
description: |
    High performance layout viewer and editor that supports GDS and OASIS files.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(ruby-2.6)
replaces   :
    - klayout-devel
setup      : |
    ./build.sh -dry-run -qt5 -rpath %libdir%/klayout
build      : |
    %make -C build-release
install    : |
    # install to bin-release
    make -C build-release install

    ## Binaries
    install -Ddm 00755 $installdir/usr/bin
    install -m 00755 bin-release/{klayout,strm*} $installdir/usr/bin/.

    ## Libraries and Plugins
    for subdir in "." "db_plugins" "lay_plugins"; do
        install -Ddm 00755 $installdir/%libdir%/klayout/${subdir}
        cp -d bin-release/${subdir}/*.so $installdir/%libdir%/klayout/${subdir}/.
        cp -d bin-release/${subdir}/*.so.* $installdir/%libdir%/klayout/${subdir}/.
        chmod 00644 $installdir/%libdir%/klayout/${subdir}/*.so
        chmod 00644 $installdir/%libdir%/klayout/${subdir}/*.so.*
    done

    ## Python packages
    sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
    install -Ddm 00755 $installdir/${sitedir}/klayout
    install -Ddm 00755 $installdir/${sitedir}/klayout/${subdir}
    install -m 00644 bin-release/pymod/klayout/{*.py,*.so} $installdir/${sitedir}/klayout/.
    for subdir in db lib rdb tl; do
        install -Ddm 00755 $installdir/${sitedir}/klayout/${subdir}
        install -m 00644 bin-release/pymod/klayout/${subdir}/*.py $installdir/${sitedir}/klayout/${subdir}/.
    done
    install -Ddm 00755 $installdir/${sitedir}/pya
    install -m 00644 bin-release/pymod/pya/*.py $installdir/${sitedir}/pya/.

    ## Menu Files
    install -Dm 00644 etc/logo.png $installdir/usr/share/pixmaps/klayout.png
    install -Dm 00644 $pkgfiles/klayoutEditor.desktop $installdir/usr/share/applications/klayoutEditor.desktop
    install -Dm 00644 $pkgfiles/klayoutViewer.desktop $installdir/usr/share/applications/klayoutViewer.desktop
