name       : klayout
version    : '0.25'
release    : 1
source     :
    - http://www.klayout.org/downloads/source/klayout-0.25.tar.gz : 645865a070f3cbd58eb2d1415e5e34ac363cbdc916a99d6ca75dd7cf8a82af40
license    :
    - GPL-2.0
summary    : Klayout GDS/OASIS editor.
component  : office.scientific
description: |
    High performance layout viewer and editor that supports GDS and OASIS files.
builddeps  :
    - pkgconfig(harfbuzz)
    - pkgconfig(gl)
    - pkgconfig(QtCore)
    - pkgconfig(python-3.5)
    - pkgconfig(ruby-2.3)
setup      : |
    ./build.sh -dry-run
    cd src
    %qmake4
build      : |
    cd src
    %make
install    : |
    ## Binaries
    install -d $installdir/usr/bin
    cp -a src/{klayout,strm*} $installdir/usr/bin
    chmod -R 00755 $installdir/usr/bin
    ## Libraries
    install -d $installdir/usr/lib64
    cp -a src/libklayout* $installdir/usr/lib64
    chmod -R 00644 $installdir/usr/lib64
    ## Menu Files    
    install -D -m 00644 etc/logo.png $installdir/usr/share/pixmaps/klayout.png
    install -D -m 00644 $pkgfiles/klayoutEditor.desktop $installdir/usr/share/applications/klayoutEditor.desktop
    install -D -m 00644 $pkgfiles/klayoutViewer.desktop $installdir/usr/share/applications/klayoutViewer.desktop

