name       : klayout
version    : 0.28.9
release    : 36
source     :
    - https://github.com/KLayout/klayout/archive/v0.28.9.tar.gz : c0b773278527524ddcc3f32333ee09c39cf4a0fd4685d92b81a040c021e3043a
homepage   : https://www.klayout.de/
license    :
    - GPL-2.0-or-later
component  : office.scientific
summary    : Klayout GDS/OASIS editor
description: |
    High performance layout viewer and editor that supports GDS and OASIS files.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(python3)
    - pkgconfig(ruby-3.2)
replaces   :
    - klayout-devel
setup      : |
    ./build.sh -dry-run -qt5 -rpath %libdir%/klayout
build      : |
    %make -C build-release
install    : |
    # install to bin-release
    make -C build-release install

    ## Binaries
    install -dm00755 $installdir/usr/bin
    install -m00755 bin-release/{klayout,strm*} $installdir/usr/bin/.

    ## Libraries and Plugins
    for subdir in "." "db_plugins" "lay_plugins"; do
        install -dm00755 $installdir/%libdir%/klayout/${subdir}
        cp -d bin-release/${subdir}/*.so $installdir/%libdir%/klayout/${subdir}/.
        cp -d bin-release/${subdir}/*.so.* $installdir/%libdir%/klayout/${subdir}/.
        chmod 00644 $installdir/%libdir%/klayout/${subdir}/*.so
        chmod 00644 $installdir/%libdir%/klayout/${subdir}/*.so.*
    done

    ## Python packages
    sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
    install -dm00755 $installdir/${sitedir}/klayout
    install -dm00755 $installdir/${sitedir}/klayout/${subdir}
    install -m00644 bin-release/pymod/klayout/{*.py,*.so} $installdir/${sitedir}/klayout/.
    for subdir in db lib rdb tl lay; do
        install -dm00755 $installdir/${sitedir}/klayout/${subdir}
        install -m00644 bin-release/pymod/klayout/${subdir}/*.py $installdir/${sitedir}/klayout/${subdir}/.
    done
    install -dm00755 $installdir/${sitedir}/pya
    install -m00644 bin-release/pymod/pya/*.py $installdir/${sitedir}/pya/.

    ## Menu Files
    install -Dm00644 etc/logo.png $installdir/usr/share/pixmaps/klayout.png
    install -Dm00644 $pkgfiles/klayoutEditor.desktop $installdir/usr/share/applications/klayoutEditor.desktop
    install -Dm00644 $pkgfiles/klayoutViewer.desktop $installdir/usr/share/applications/klayoutViewer.desktop
